name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          make build
          scp -i ~/.ssh/id_rsa ./bin/hub ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/root/hub
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} "nohup /root/hub --config /root/hub/config.yaml > /dev/null 2>&1 &"
