name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Test sshpass
        run: sudo sshpass -v -p "${{ secrets.SSH_PWD }}" ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}" "pwd"
      - name: Build
        run: make build
      - name: Deploy
        run: |
          sudo sshpass -p "${{ secrets.SSH_PWD }}" scp "./bin/hub" "${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/root/hub"
          sudo sshpass -p "${{ secrets.SSH_PWD }}" ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}" "nohup /root/hub --config /root/hub/config.yaml > /dev/null 2>&1 &"
