name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Test sshpass
        env: # Or as an environment variable
          SSH_PWD: ${{ secrets.SSH_PWD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: ｜
          echo $SSH_SERVER
          echo $MY_SECRET
          sshpass -v -p "$SSH_PWD" ssh "$SSH_USER@$SSH_SERVER" "pwd"
      - name: Build
        run: make build
      - name: Deploy
        env: # Or as an environment variable
          SSH_PWD: ${{ secrets.SSH_PWD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
        run: |
          sshpass -v -p "$SSH_PWD" scp "./bin/hub" "$SSH_USER@$SSH_SERVER:/root/hub"
          sshpass -v -p "$SSH_PWD" ssh "$SSH_USER@$SSH_SERVER" "nohup /root/hub --config /root/hub/config.yaml > /dev/null 2>&1 &"
